resource "aws_lambda_function" "paymenthMethods" {}
resource "aws_lambda_function" "reservationPaymentTransaction_dev_IHW" {}
resource "aws_lambda_function" "ancillarySearch" {}
resource "aws_lambda_function" "addancillary-hoper-dev-web" {}
resource "aws_lambda_function" "voucherCode" {}
resource "aws_lambda_function" "klaviyo_event_dev" {}
resource "aws_lambda_function" "flightSearch_dev_Website" {}
resource "aws_lambda_function" "accessibilityRequest_Website_Dev" {}
resource "aws_lambda_function" "baggage" {}
resource "aws_lambda_function" "voucherCode_Web_Dev" {}
resource "aws_lambda_function" "reservationPatmentTransaction" {}
resource "aws_lambda_function" "seatSealection" {}
resource "aws_lambda_function" "Website_Dev_LamdaAuthoriser" {}
resource "aws_lambda_function" "flightSelection_dev_Web" {}
resource "aws_lambda_function" "lambdaFunction-dev" {}
resource "aws_lambda_function" "flightSearch" {}
resource "aws_lambda_function" "createReservation_Web_Dev" {}
resource "aws_lambda_function" "test_calender" {}
resource "aws_lambda_function" "brb_purchaseService_dev_Web" {}
resource "aws_lambda_function" "Website_Dev_CalenderRates" {}
resource "aws_lambda_function" "flair-hopper-api" {}
resource "aws_lambda_function" "lowFareoptions_Dev_Website" {}
resource "aws_lambda_function" "JWTtoken_Website_Dev" {}